version: "3.4"

services:
  webserver:
    container_name: sesab_api
    build:
      context: ./
      target: dev
      dockerfile: ./.devops/php/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "${APP_PORT:-8000}:80"
    entrypoint: ./.devops/entrypoint.sh
    depends_on:
      - database
      - cacheserver
    networks:
      - webserver

  database:
    container_name: sesab_database
    image: mariadb:10.6-focal
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      - webserver

  database:
    container_name: mariadb-2
    image: mariadb:10.6-focal
    environment:
      MYSQL_DATABASE: "${DB_DATABASE:-sesab_api}"
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  cacheserver:
    container_name: redis_server-2
    image: redis:7.0.12-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"

networks:
  webserver:
    driver: bridge
