version: "3.4"

services:
  webserver:
    container_name: sesab_api
    command: php artisan serve
    build:
      context: .
      dockerfile: ./.devops/php/Dockerfile
    ports:
      - '${APP_PORT:-8000}:8000'
    volumes:
      - .:/var/www/sesab_app
    depends_on:
      - database
      - cacheserver

  database:
    container_name: sesab_database
    image: mariadb:10.6-focal
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "${DB_PORT:-3306}:3306"

  cacheserver:
    container_name: redis_server
    image: redis:7.0.12-alpine
    ports:
      - "6379:6379"
